### ISSUE TITLE
Launchpad: Make "+Model" Button open create model modal

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#1922] opened 2023-03-14 23:41 UTC
I created a new instance and realized that the "+Model" Button does not open the create a model screen but rather the all models screen. May we please update this?

<img width="1382" alt="CleanShot 2023-03-14 at 16 39 48@2x" src="https://user-images.githubusercontent.com/22625919/225165921-3866df76-d914-47f6-941e-4cef9c25ca34.png">

**Comment by theofficialnar** [comment] 2023-05-24 21:23
Seems like this is already working as intended. Can we close this @zcolah and @agalin920 ?

**Comment by theofficialnar** [comment] 2023-05-24 22:16
Ah I thought this was about the Create model option on the floating + button, my bad. 🤦‍♂️

**Closed** 2023-06-07 22:00 UTC
Labels: bug
