### ISSUE TITLE
Content Version Rollbacks not working

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/manager-ui#770] opened 2021-06-22 22:58 UTC
Hello, if I click back to a previous version of content it is not loading. Also, the preview button to preview a specific version doesn't append the query parameter to preview that version.

**Comment by shrunyan** [comment] 2021-06-23 20:21
Duplicate of https://github.com/zesty-io/manager-ui/issues/614

**Closed by shrunyan** 2021-06-23 20:21 UTC
