### ISSUE TITLE
Indicate to user when a one-to-many field limit has been reached and a second field will be necessary

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/manager-ui#897] opened 2021-09-17 18:08 UTC
**Describe the bug**
When a one-to-many field character limit has been reached: 
* the UX does not indicate this to the user, does not highlight an additional on-to-many field is needed and the Content Item will then no longer save
* no UX indicators for the user as to why the item is unable to be save 
* the API does not return a 500 or message informing user the limit has been reached

**To Reproduce**
1. create one-to-many field
2. exceed number of allowable related item zuids
3. try to save the content item
**in API exceed the related item zuids and view response

**Enhancement behavior**
An indicator that the limit has been met for the one-to-many, the unable to save alert indicates why it can't be saved, an additional alert to inform the user to add in another field, response from the API informs user limit reached or 500

**Comment by agalin920** [comment] 2022-03-28 17:11
Duplicate of https://github.com/zesty-io/manager-ui/issues/623

**Closed** 2022-03-29 02:09 UTC
Labels: enhancement

**Comment by giseleblair** [comment] 2022-03-29 07:44
@agalin920 seeing this marked as closed, what was the solution?

**Comment by agalin920** [comment] 2022-03-29 23:21
@giseleblair https://github.com/zesty-io/design-system/pull/165

please let me know if there is any additional work and we can reopen
