### ISSUE TITLE
Content: Publish Status Tab - Live Chip Text is White (Should be Success/Dark)

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2962] opened 2024-09-17 17:24 UTC
![Image](https://github.com/user-attachments/assets/cabf5c66-86fe-4c27-90a7-58a2d4191a97)

**Comment by finnar-bin** [comment] 2024-10-09 21:48
Duplicate of #2795

**Closed** 2024-10-09 22:18 UTC
Labels: bug
