### ISSUE TITLE
Character counts on all field creation inputs in the schema app do not update

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/manager-ui#1179] opened 2022-06-16 17:45 UTC
**Describe the bug**
When adding fields to a model's schema the inputs' character counts do not update as the input values are updated.

**To Reproduce**
1. Go to schema
2. Click on any model schema
3. Add a field or use an existing field and edit the input values
4. the character count will not update as the input value is changed

**Expected behavior**
character count reflects the value character count in the input

**Screenshots**

**Video:**
![char-count](https://user-images.githubusercontent.com/50595614/174130243-2eed354b-5b5d-4492-918c-42af56e9c92b.gif)

**Comment by agalin920** [comment] 2022-07-01 04:41
Duplicate of https://github.com/zesty-io/manager-ui/issues/1179

**Closed by agalin920** 2022-07-01 04:41 UTC
Labels: bug
