### ISSUE TITLE
Duplicate item fails

### ISSUE THREAD

**Issue by gtllien** [zesty-io/manager-ui#2691] opened 2024-04-22 17:07 UTC
**Describe the bug**
Duplicating an item fails when the meta description of the item to be duplicated has 160 characters;

When duplicating an item, it appends the word "**(copy)**" and when the item to be copied has meta description count of 160 characters it cannot be duplicated

**To Reproduce**
1. Go to a specific content item with meta description count of 160 characters
2. Click on 'Duplicate Item'
3. Item is not duplicated but there's no error shown in UI
4. Check browser's network tool to see the error as below:
"_Bad Request: validation error: Meta Description must be shorter than 160 characters_"

**Expected behavior**
Display error message in UI so the user will know why the item cannot be duplicated;

Design limitation - can we consider not appending the word "**(copy)**" in the meta description?

**See test video capture**

https://github.com/zesty-io/manager-ui/assets/112954373/3432109f-5061-4215-a0f7-368edffa7204

**Comment by finnar-bin** [comment] 2024-04-24 21:55
Duplicate of https://github.com/zesty-io/manager-ui/issues/2669

**Comment by finnar-bin** [comment] 2024-04-24 22:14
@gtllien see note above. closing

**Closed by finnar-bin** 2024-04-24 22:14 UTC
