### ISSUE TITLE
Internal/External creation does not function in Manager UI

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#439] opened 2020-12-15 01:19 UTC
**Describe the bug**
In Manager UI - I cannot add an Internal/External link item.

**To Reproduce**
1. From the Content section - select Internal/External item from the top of the left-hand nav & below the global search
2. Select External link & try to type in a name - the textbox will not take input
3. Search for a Parent - you'll be unable to select a parent
4. Select Internal Link and try steps 3 again  - same error -they won't exist. 

**Expected behavior**
Expect parity with Legacy. Legacy still functions as expected.

**Screenshots**

<img width="1263" alt="Screen Shot 2020-12-14 at 5 15 56 PM" src="https://user-images.githubusercontent.com/16694502/102155517-8bd0c780-3e30-11eb-9b54-99d9475172b2.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 87

**Additional context**

**Comment by shrunyan** [comment] 2020-12-16 01:07
Duplicate of https://github.com/zesty-io/manager-ui/issues/292

**Closed** 2020-12-16 01:07 UTC
Labels: app: content, bug
