### ISSUE TITLE
Version control in the Code App does not load the previous version

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/manager-ui#900] opened 2021-10-06 21:46 UTC
**Describe the bug**
Version control in the Code App does not load the previous version. After selecting a previous version, the footer bucket indicates the current version is the one displayed and there are no changes to code itself. When entering the version control screen again the local version will display as though is was reverted to the previous and if the version was saved it will indicate that the new version has the revert code but won't display or apply the revert.

**To Reproduce**
Videos displaying reproduction
Step 1
https://www.loom.com/share/195e4868de254d71a42cae10e598e83b

Step 2
https://www.loom.com/share/ce278ed09e7441d99979ad811df9dc38

**Expected behavior**
When selecting to load a previous version, the version is loaded and displayed on screen and the viewing version in the footer bucket reflects this.

**Comment by d88naimi** [comment] 2021-10-29 23:06
While investigating this issue, we determined there are 2 areas that cause this.
1) https://github.com/zesty-io/manager-ui/blob/master/src/apps/code-editor/src/app/components/Editor/components/MemoizedEditor/MemoizedEditor.js#L69
The memoized function of this component will only fire a re render on the fileZUID

2)  https://github.com/zesty-io/manager-ui/blob/master/src/apps/code-editor/src/app/components/Editor/components/MemoizedEditor/MemoizedEditor.js#L25-L27
In addition the Monaco editor manages it's own internal state, as such we need to determine away to update monaco internal state when the `code` prop changes

**All of this without losing the performance benefits, the memo provides  in regards to the code value changing on every key stroke when someone types **

**Comment by agalin920** [comment] 2022-03-24 06:10
I believe this is a duplicated issue that has already been resolved

**Comment by agalin920** [comment] 2022-03-29 02:10
Duplicate of [982](https://github.com/zesty-io/manager-ui/issues/982)

**Closed** 2022-03-29 02:10 UTC
Labels: bug
