### ISSUE TITLE
DUO Mode: Switch on DUO Mode for Existing and New Customers

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2399] opened 2023-12-12 21:48 UTC
**Problem**
Customers do not know about DUO Mode and how to start it. We just want to start it for existing customers and new customers/instance in the future.

**Solution Steps**
Specifically this solution is based around a content policy setting.

- [x] 1. @giseleblair Please document the solution or assign someone to document this
- [ ] 2. There needs to be a change made to the product by the manager ui team to allow for the value that @giseleblair has documented. If there are any questions on how to go about this please ask @shrunyan. 
- [x] 3. We need to bake that value into the starter blue print, and into all of the existing templates. We want to make DUO mode the default experience for all of the templates. 
- [ ] 4. Once we complete this solution, we will lead an outreach effort to existing customers where we inform them of DUO mode, and the steps they need to set it up along with an option for a training/setup call.

**Comment by zcolah** [comment] 2023-12-21 23:24
@agalin920 this is a ticket that is WIP with Randy. Not yet assigned to any developers therefore.

**Comment by giseleblair** [comment] 2024-01-03 19:48
The following settings would be the ideal values to allow to use DUO mode within the product:
Settings: 
`Header: X-Frame-Options`
`Content-Security-Policy`
`Referrer-Policy`

![Screenshot 2023-12-13 at 4 02 35 PM](https://github.com/zesty-io/manager-ui/assets/9896546/c1055365-4917-445d-bd71-468f20f04e48)

**Comment by allenpigar** [comment] 2024-02-06 00:02
@agalin920 is there any default value for theres keys? or should i leave it null when creating this settings?

**Comment by allenpigar** [comment] 2024-02-13 12:53
@giseleblair @agalin920 i already create a branch (https://github.com/zesty-io/template-pomelo/tree/enable-duo-mode) for this, removing the setting to enable duo mode but the installer template installation does not support deletion of settings. it only updates or creates settings. with this, i think we must also need to delete those settings on the "template base blueprint" since this blueprint creates the base or default setting for the instance before the installer updates or creates the settings for template.



![Image](https://github.com/zesty-io/manager-ui/assets/50983144/ef72d2d9-3b06-440d-b7e7-1c9aaf23ee53)

**Comment by giseleblair** [comment] 2024-02-13 17:19
I believe that template base blueprint only exists in the database, can you confirm @allenpigar

**Comment by allenpigar** [comment] 2024-02-15 00:30
@giseleblair yes it exist on the database and sql scripts are need to update. but as we have discussed, there no need to remove those settings and just set the default value to null. with this, we can just update the values on the template itself without any changes on the blueprint. i already created pr for review.

https://github.com/zesty-io/template-blank/pull/2
https://github.com/zesty-io/template-simple-blog/pull/1
https://github.com/zesty-io/template-pomelo/pull/3

**Comment by finnar-bin** [comment] 2024-08-19 01:14
@giseleblair it seems like there's nothing needed to done in manager-ui for this ticket anymore as I tried creating new instances using all the existing templates are they all have duo mode enabled by default already.

I checked in with @allenpigar and he has confirmed that he changed the template's default values for the following settings (basic_content_api_key, headless_authorization_key, authorization_key and x_frame_options) to `null` which is what manager-ui needs for duo mode to be enabled. Therefore it doesn't seem like any work needs to be done in the manager-ui since duo mode is now enabled by default when creating new instances using the templates.

**Comment by giseleblair** [comment] 2024-08-19 01:35
@finnar-bin please refer to my screenshot above in the thread (from Jan 3) and test with those values. Duo mode needs to work with the those values not just the null values from the templates

**Comment by finnar-bin** [comment] 2024-08-19 05:37
@giseleblair so does that mean duo mode should be activated if those settings are null **or** contain the values you mentioned?

**Comment by giseleblair** [comment] 2024-08-19 13:38
@finnar-bin Duo mode does not get activated by these settings. But the goal is that when Duo Mode is turned on, AND the above settings are either null or the specific mentioned values that the Duo Mode frame will render the page as expected. Currently, the values MIUST be null in order for the Duo Mode frame to render. But we want to update this logic so it will also work with the mentioned values.

**Comment by finnar-bin** [comment] 2024-08-28 22:32
Note to self: CSP needs to be validated as well

**Comment by finnar-bin** [comment] 2024-09-06 06:21
@giseleblair is there a need to validate that the value for Referrer-Policy be either null or "strict-origin-when-cross-origin" for the duo mode toggle to be visible?

**Comment by giseleblair** [comment] 2024-09-11 21:51
I believe that CSP will trump the Referrer-Policy value @finnar-bin but it is still worth validating in the order of operations

**Closed** 2024-09-18 23:33 UTC
Labels: enhancement
